# Generated by Django 3.0.6 on 2020-05-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_map', '0002_auto_20200520_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='picture',
        ),
        migrations.AddField(
            model_name='trip',
            name='country_pic',
            field=models.ImageField(blank=True, upload_to='scratch_map/images'),
        ),
    ]
