# Generated by Django 3.0.6 on 2020-05-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_map', '0003_auto_20200520_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='country_pic',
            new_name='trip_img',
        ),
    ]
