# Generated by Django 3.0.6 on 2020-05-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_map', '0004_auto_20200527_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default='AAA', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='country_type',
            field=models.CharField(default='AAA', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='country_coordinates',
            field=models.TextField(),
        ),
    ]
