# Generated by Django 3.0.6 on 2020-05-30 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scratch_map', '0006_auto_20200528_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
