# Generated by Django 3.0.6 on 2020-06-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_map', '0014_auto_20200629_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['country_name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
