# Generated by Django 3.0.6 on 2020-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_map', '0015_auto_20200629_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='note',
            field=models.TextField(max_length=10),
        ),
    ]
