# Generated by Django 3.0.6 on 2020-07-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch_map', '0016_auto_20200710_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='note',
            field=models.TextField(max_length=750),
        ),
    ]
